// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: health.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceHealthCheckClient is the client API for ServiceHealthCheck service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceHealthCheckClient interface {
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type serviceHealthCheckClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceHealthCheckClient(cc grpc.ClientConnInterface) ServiceHealthCheckClient {
	return &serviceHealthCheckClient{cc}
}

func (c *serviceHealthCheckClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/ServiceHealthCheck/check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceHealthCheckServer is the server API for ServiceHealthCheck service.
// All implementations must embed UnimplementedServiceHealthCheckServer
// for forward compatibility
type ServiceHealthCheckServer interface {
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedServiceHealthCheckServer()
}

// UnimplementedServiceHealthCheckServer must be embedded to have forward compatible implementations.
type UnimplementedServiceHealthCheckServer struct {
}

func (UnimplementedServiceHealthCheckServer) Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedServiceHealthCheckServer) mustEmbedUnimplementedServiceHealthCheckServer() {}

// UnsafeServiceHealthCheckServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceHealthCheckServer will
// result in compilation errors.
type UnsafeServiceHealthCheckServer interface {
	mustEmbedUnimplementedServiceHealthCheckServer()
}

func RegisterServiceHealthCheckServer(s grpc.ServiceRegistrar, srv ServiceHealthCheckServer) {
	s.RegisterService(&ServiceHealthCheck_ServiceDesc, srv)
}

func _ServiceHealthCheck_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHealthCheckServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServiceHealthCheck/check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHealthCheckServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceHealthCheck_ServiceDesc is the grpc.ServiceDesc for ServiceHealthCheck service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceHealthCheck_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ServiceHealthCheck",
	HandlerType: (*ServiceHealthCheckServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "check",
			Handler:    _ServiceHealthCheck_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health.proto",
}
